### ISSUE TITLE
Bad Request: entity begins in a middle of a UTF-16 symbol at byte offset ...

### ISSUE THREAD

**Issue by abakum** [mymmrac/telego#94] opened 2023-04-13 14:22 UTC
### 💬 Telego version

0.22.0

### 👾 Issue description

`entitys := []tu.MessageEntityCollection{}
entitys = append(entitys, tu.Entity("🌗"))
bot.SendMessage(tu.MessageWithEntities(tu.ID(ctm.Chat.ID), entitys...).WithReplyToMessageID(ctm.MessageID))
//[Thu Apr 13 13:07:41 MSK 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/sendMessage", with data: {"chat_id":1,"text":"🌗Last quarter","entities":[{"type":"code","offset":1,"length":12}],"reply_to_message_id":1}
//[Thu Apr 13 13:07:41 MSK 2023] DEBUG API response sendMessage: Ok: false, Err: [400 "Bad Request: entity begins in a middle of a UTF-16 symbol at byte offset 4"]
`
Please look:
https://core.telegram.org/bots/api#messageentity
MessageEntity
...
offset	Integer	Offset in UTF-16 code units to the start of the entity
length	Integer	Length of the entity in UTF-16 code units
...
https://core.telegram.org/api/entities#entity-length
Computing entity length
Code points in the BMP (U+0000 to U+FFFF) count as 1, because they are encoded into a single UTF-16 code unit
Code points in all other planes count as 2, because they are encoded into two UTF-16 code units (also called surrogate pairs)
...
However, since UTF-8 encodes codepoints in non-BMP planes as a 32-bit code unit starting with 0b11110, a more efficient way to compute the entity length without converting the message to UTF-16 is the following:

If the byte marks the beginning of a 32-bit UTF-8 code unit (all bytes starting with 0b11110) increment the count by 2, otherwise
If the byte marks the beginning of a UTF-8 code unit (all bytes not starting with 0b10) increment the count by 1.
Example:

length := 0
for byte in text {
    if (byte & 0xc0) != 0x80 {
        length += 1 + (byte >= 0xf0)
    }
}
Note: the length of an entity must not include the length of trailing newlines or whitespaces, rtrim entities before computing their length: however, the next offset must include the length of newlines or whitespaces that precede it.

### ⚡️ Expected behavior

{code 2 12  <nil>  }

### 🧐 Code example

```Go
`					entitys := []tu.MessageEntityCollection{}
					entitys = append(entitys, tu.Entity("🌗"))
					t, es := tu.MessageEntities(entitys...)
					stdo.Printf("%U %v %v\n", []rune(t)[0], []byte(t), es) //15:46:48 main.go:471: U+1F317 [240 159 140 151] []
					entitys = append(entitys, tu.Entity("Last quarter").Code())
					t, es = tu.MessageEntities(entitys...)
					stdo.Printf("%s %v\n", t, es) //15:46:48 main.go:474: 🌗Last quarter [{code 1 12  <nil>  }]
					bot.SendMessage(tu.MessageWithEntities(tu.ID(ctm.Chat.ID), entitys...).WithReplyToMessageID(ctm.MessageID))
//[Thu Apr 13 13:07:41 MSK 2023] DEBUG API call to: "https://api.telegram.org/botBOT_TOKEN/sendMessage", with data: {"chat_id":1,"text":"🌗Last quarter","entities":[{"type":"code","offset":1,"length":12}],"reply_to_message_id":1}
//[Thu Apr 13 13:07:41 MSK 2023] DEBUG API response sendMessage: Ok: false, Err: [400 "Bad Request: entity begins in a middle of a UTF-16 symbol at byte offset 4"]
`
```

**Comment by abakum** [comment] 2023-04-13 19:57
Dirty hack:
```
// MessageEntities coverts entity collections into the text and slice of telego.MessageEntity associated with that text
func MessageEntities(entityCollections ...MessageEntityCollection) (string, []telego.MessageEntity) {
	text := strings.Builder{}
	var entities []telego.MessageEntity

	for _, collection := range entityCollections {
		// collection.SetOffset(utf8.RuneCountInString(text.String()))
		collection.SetOffset(len(utf16.Encode([]rune(text.String()))))
		entities = append(entities, collection.Entities()...)

		_, _ = text.WriteString(collection.Text())
	}

	return text.String(), entities
}
```

**Comment by mymmrac** [comment] 2023-04-14 15:16
This issue is partially fixed by #95, but still the length of trailing newlines or whitespace is not counted correctly, I will fix that soon (hopefully)

**Comment by mymmrac** [comment] 2023-04-30 10:16
Fixed in [v0.23.0](https://github.com/mymmrac/telego/releases/tag/v0.23.0), now new lines & whitespaces counted correctly

**Comment by mymmrac** [comment] 2023-05-01 11:06
Trimmed to much, only left spaces should be trimmed

**Comment by abakum** [comment] 2023-05-01 11:19
Only right space must be trimmed rtrim

**Comment by mymmrac** [comment] 2023-05-03 21:36
I investigated a lot and here are some of my findings:

1. Telegram's clients does not treat message entities the same as bots
2. If you for example will send `a* test *_b_` though bot, the entities will be: `[{offset: 2, length: 5}, {offset: 7, length: 1}]`, which really doesn't make sense, because according to docs `* test *` should be at offset 1, not 2. Having it with offset 2 it should be of length 4 since we are trimming trailing spaces, but it's of length 5
3. I will not make 100% one to one entity handling any way, because it's much more complex than it seems (Telegram actually combines same entities into one and does more stuff with it), so the goal is just to get it working in any case, but it's non-necessary means to work 100% as Telegram does as long as the result is the same

Most importantly, from now on any issues related to entity length or entity count, or anything related to entities that is not breaking or disallowing to achieve certain result will not be worked on. If you are not able to send something properly, yes, it's a bug, but if it sends as expected, and you were expecting a different result from Telegram then what Telego produced - it's how things will work, it's not a bug

**Closed** 2023-05-03 21:37 UTC
Labels: :space_invader: Bug, :no_entry_sign: Won't Fix

**Comment by mymmrac** [comment] 2023-05-03 22:16
Updates on this in [v0.24.0](https://github.com/mymmrac/telego/releases/tag/v0.24.0)

**Comment by abakum** [comment] 2023-05-04 06:35
> 1. Telegram's clients does not treat message entities the same as bots
IMHO the specification is more important than the implementation, since implementation errors are possible:
– Командир говорит: «Делай как я!», а комиссар говорит: «Делай, как я говорю!»
\8^)

**Comment by abakum** [comment] 2023-05-04 07:27
telego bot send `a* test *_b_` as is
![image](https://user-images.githubusercontent.com/18271863/236136568-89877f9b-9b24-4ec4-af0c-03350741080a.png)
```
			bot.SendMessage(tu.Message(tu.ID(tm.Chat.ID),
				"😅** test **🌗",
			))
			bot.SendMessage(tu.Message(tu.ID(tm.Chat.ID),
				"a* test *_b_",
			))

```
web client send  `a* test *_b_` as is
windows desktop client send  `a* test *_b_` as is
web client send  `😅** test **🌗` as 
![image](https://user-images.githubusercontent.com/18271863/236137815-7875e299-df4f-4a06-9fc4-76f628d6bd08.png)

windows desktop client send  `😅** test **🌗` as is

**Comment by mymmrac** [comment] 2023-05-04 07:34
When using bots, it's required to specify `ParseMode` to any formatting to work

**Comment by abakum** [comment] 2023-05-04 07:53
"text":"😅** test **🌗","parse_mode":"MarkdownV2"
"text":"\ud83d\ude05 test \ud83c\udf17"}

"text":"a* test *_b_","parse_mode":"MarkdownV2"}
"text":"a test b","entities":[{"offset":2,"length":5,"type":"bold"},{"offset":7,"length":1,"type":"italic"}]}
You are right!

**Comment by abakum** [comment] 2023-05-04 07:59
> Note: the length of an entity must not include the length of trailing newlines or whitespaces, rtrim entities before computing their length: _however, the next offset must include the length of newlines or whitespaces that precede it_.

> 2\. because according to docs `* test *` should be at offset 1, not 2.
As I understand docs offset should be 2

**Comment by abakum** [comment] 2023-05-04 08:12
> however, the next offset must include the length of newlines or whitespaces that precede it

Please look second part of note

**Comment by mymmrac** [comment] 2023-05-04 08:28
Yep, so this text `a* test *b` according to the docs what we do:
1. We have an entity `_test_` (replaced spaces with underscores to be more obvious) that should be bold
2. We should `rtrim` the entity, so  `_test_` becomes  `_test`, which make sense
3. The length now is 5, which is correct
4. The offset according to the docs must include the length of newlines or whitespaces that precede it, **but** `a` in a text is not an entity, it's plain text (and Telegram treats is as plain text, because in response we are getting only 1 entity) => no trailing spaces counted (and if they were, its `a` not `a_`)
5. Offset clearly should be 1, because before `_test` we have only 1 char (`a`)
6. Telegram says that the offset should be 2, 2? How????

From docs what is expected:  `a* test *b`  => `[{offset: 1, length: 5}]`

What actually returned by Telegram:   `a* test *b`  => `[{offset: 2, length: 5}]`

Don't get me wrong, in both cases the result will actually be correct, since in both cases non-space part of entity (text `test`) will be bold as we expected, just the representation is different

**Comment by mymmrac** [comment] 2023-05-04 08:35
In any case, trimming entities from left, right, both, actually will limit what bot can send, here is why:

Imagine you want to send code, here are some cases when trimming in any way makes it impossible to send the expected message:
1. <code>\`_test\`a</code> (`ltrim` will not allow leading space)
2. <code>\`test\_\`a</code> (`rtrim` will not allow trailing space)
3. <code>\`_test\_\`a</code> (`trim` will not allow both leading and trailing space)

**Comment by mymmrac** [comment] 2023-05-04 08:38
Here is example of this exact cases in official Telegram client:
![image](https://user-images.githubusercontent.com/39216424/236153409-69f9c9e1-76df-4166-b016-3257fe4619e2.png)

**Comment by abakum** [comment] 2023-05-04 08:54
> 5\. Offset clearly should be 1, because before `_test` we have only 1 char (`a`)

offset `a` is 0
offset `_text` is 1
offset ` _text` by docs is 2=1+len(_) //offset must include the length of newlines or whitespaces that precede it
Now telegram does not swear at incorrect offsets and lengths, but simply corrects them, but what will happen tomorrow?

**Comment by mymmrac** [comment] 2023-05-04 09:17
If you know the way to count offsets & length correctly and still be able to send all messages that are possible to send right now, please either explain it to me, or write a pull request, it will be very welcomed.

Telegram is constantly changing, breaking things from one update to another, if they will decide to change the behavior, sure, why not, I just will update Telego as usual, but breaking some working functionality of Telego right now to "properly count offsets" even if it doesn't matter, for what? To know that it counts it correctly, but now you can't send some messages now?

**Comment by abakum** [comment] 2023-05-04 10:21
А неприятности будем переживать по мере их поступления, а еще лучше не переживать, а идти дальше.
© Михаил Жванецкий
\8^)
